config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :drivers, only: [:index, :new, :create, :show]

  get "users/:id/drivers", to: "users#drivers", as: :user_bookings
  resources :drivers do
    resources :bookings, only: [:new, :create]
    # changed it from universal resources to only new and create as needed
  end
  resources :bookings, except: [:new, :create]
end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :driver

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/driver.rb
class Driver < ApplicationRecord
  #belongs_to :user
  validates :name, :license_type, :years_driving, :transmission, :location, :price, presence: true
  has_one_attached :photo
  has_many :bookings
  # belongs_to :user

  # [...]
  include PgSearch::Model
  pg_search_scope :search_by_location,
    against: [ :location ],
    using: {
      tsearch: { prefix: true }
    }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :drivers
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def new
    set_driver
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    set_driver
    @booking.driver = @driver
    @user = current_user
    @booking.user = @user
    if @booking.save
      redirect_to @booking
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @driver = @booking.driver
  end

  def update
    @booking = Booking.find(params[:id])

    if @booking.update(booking_params)
      redirect_to @booking
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    driver = @booking.driver
    @booking.destroy
    redirect_to driver_path(driver)
  end

  private

  def set_driver
    @driver = Driver.find(params[:driver_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/driver_controller.rb
class DriverController < ApplicationController
  def index
    @drivers = Driver.all
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    if params[:query]
      @drivers = Driver.search_by_location(params[:query])
    else
      @drivers = Driver.all
    end
    @markers = @drivers.geocoded.map do |driver|
      {
        lat: driver.latitude,
        lng: driver.longitude,
        info_window: render_to_string(partial: "/drivers/map_window", locals: { driver: driver })
      }
    end
  end
# resave it
  def show
    @driver = Driver.find(params[:id])
    @booking = Booking.new
  end

  def new
    @driver = Driver.new
  end

  def create
    @driver = Driver.new(strong_params)
    # @driver.user = current_user
    if @driver.save!
      redirect_to driver_path(@driver)
    else
      render :new
    end
  end

  def destroy
    @driver = Driver.find(params[:id])
    @driver.destroy
    redirect_to drivers_path, notice: "Driver was successfully deleted"
    # redirect_to user_path(@driver.user.id)
  end

  private

  def strong_params
    params.require(:driver)
          .permit(:name, :license_type, :years_driving, :transmission, :price, :location, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def drivers
    @bookings = current_user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="small-container">
    <h1>Change a booking for <%= @driver.name %></h1>
    <p><%= @driver.name %></p>
    <%= simple_form_for(@booking) do |f| %>
     <%= f.input :start_date, html5: true  %>
     <%= f.input :end_date, html5: true  %>
     <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="small-container">
<h1>Add a booking for <%= @driver.name %></h1>
  <%= simple_form_for [@driver, @booking] do |f| %>
    <%= f.input :start_date, html5: true  %>
    <%= f.input :end_date, html5: true  %>
    <%= f.button :submit, class: "btn-warning create-booking" %>
  <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <h1><strong>Congratulations</strong>, you have successfully booked <%= @booking.driver.name %> as your driver.</h1>
        <h3> Your car will be driven <strong> wherever </strong> safely. </h3>
    </div>
  </div>
</div>
<div class="container btn-container mt-2">
    <div class="d-flex justify-content-around">
      <div class="btn-yellow mr-2" style="width: 100%;">
        <%= link_to edit_booking_path(@booking) do %>
          <p class="mb-0 text-left"><i class="fas fa-directions"></i> Edit Booking</p>
        <% end %>
      </div>
    </div>
  </div>

app/views/drivers/_map_window.html.erb
<h2><%= driver.name %></h2>
<p><%= driver.location %></p>
<%= link_to "Book driver", driver_path(driver), class: 'btn btn-secondary' %>

app/views/drivers/index.html.erb
<div class="searchbardrivers">
  <h2>Our Drivers</h2>

    <%= form_tag drivers_path, method: :get do %>
      <div class="search-form-control form-group m-5">
      <%= text_field_tag :query,
      params[:query],
      class: 'form-control string required', id: 'search_query',
      placeholder:'search location'%>
      <%= submit_tag "Search", class: "btn btn-flat"%>
      </div>
    <% end %>
</div>

<div class="main-container">
  <div class="cards">
    <% @drivers.each do |driver| %>
      <div class="card-driver">
        <% if driver.photo.attached? %>
          <%= cl_image_tag driver.photo.key, height: 200, width: 200, crop: :fill %>
        <% else %>
          <% false %>
        <% end %>
        <div class="card-details">
            <h3><%= driver.name %></h3>
            <p>license type:  <%= driver.license_type %></p>
            <p><strong> <%= driver.years_driving%> years of experience</strong></p>
            <p>location:  <%= driver.location %></p>
            <%= link_to "Read more", driver_path(driver), class: 'btn btn-secondary' %>
        </div>
      </div>
    <% end %>
  </div>
  <div id="map"
    style="width: 40%; height: 100vh;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/drivers/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
  <%= simple_form_for [@user, @driver] do |f| %>
    <%= f.input :name %>
    <%= f.input :license_type %>
    <%= f.input :years_driving %>
    <%= f.input :transmission %>
    <%= f.input :location %>
    <%= f.input :price %>
    <%= f.input :photo %>
    <%= f.submit "Submit as a driver", class: "btn btn-primary btn-lg btn-block" %>
  <% end %>
</div>
  </div>
    </div>

app/views/drivers/show.html.erb
<div class="container" >
  <div class="card show-form">
    <div class="d-flex justify-content-center" style= "margin: 80px" style="width: 30rem;">
      <div class="card" style="width: 30rem;">
        <%= cl_image_tag @driver.photo.key, height: 400, width: 478, crop: :fill, alt:"Generic placeholder image" %>
          <div class="card-body">
          <h3 class="card-title"><%= @driver.name %></h3>
          <div class="card-text">
          <p>License type: <%= @driver.license_type %></p>
          <p>Years of driving: <%= @driver.years_driving %></p>
          <p>Transmission: <%= @driver.transmission %></p>
          <p>Availability: <%= @driver.availability %></p>
          <p>Location: <%= @driver.location %></p>
          <p>Price: <%= @driver.price %>$ per day</p>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card booking-form">
      <h1>Add a booking for <%= @driver.name %></h1>
        <%= simple_form_for [@driver, @booking] do |f| %>
        <%= f.input :start_date, html5: true  %>
        <%= f.input :end_date, html5: true  %>
        <%= f.button :submit, class: "btn-warning create-booking" %>
      <% end %>
    </div>
  </div>
</div>

<!--<h4><strong>Book this driver <%= @driver.name %></strong></h4>-->
<!--<p><%= @driver.price %> $ per day</p>-->
<%#= simple_form_for [@driver, @booking] do |f| %>
<%#= f.button :submit, class: "btn btn-success" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DRIVEN</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
     <div class="d-flex flex-column min-vh-100">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <article class="flex-grow-1">
        <%= yield %>
      </article>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url(https://images.unsplash.com/photo-1518783211485-10fd3bfb2ce2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1932&q=80);">
  <div class="text-center" class="container">
    <h1>DRIVEN</h1>
      <div class="typewriter">
      <p> Want your car driven from anywhere, to anywhere?</p>
      </div>
  <br>
  <br>
  <%= link_to "Let's go", drivers_path, class: "btn btn-outline-light btn-lg"%>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<hr size="6" width="70%" color="$footergray">
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/?hl=en" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/?lang=en" target="_blank"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    © 2022 DRIVEN. All rights reserved.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-wagon-fixed">
  <div class="container-fluid">
    <%= link_to root_path, class:"text-decoration-none" do  %>
      <%= image_tag("steering-wheel.png", size: "40x40") %>
      <span id="title"> DRIVEN </span>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%if user_signed_in? %>
          <li class="nav-item active">
            <%=link_to "Become a driver", new_driver_path , class: "nav-link driver" %>
          </li>
             <li class="nav-item">
            <%= link_to "View drivers", drivers_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://images.unsplash.com/photo-1600267185393-e158a98703de?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", edit_user_registration_path(current_user), class: "dropdown-item" %>
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class:"btn btn-outline-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/drivers.html.erb
<div class="container mt-5">
  <h1 class="headers">Your drivers</h1>
</div>
<div class="container mt-4 border-bottom border-warning border-10 d-flex justify-content-start">
  <button class="btn btn-bookings cars-tab" data-target="my-drivers">Cars</button>
  <button class="btn btn-bookings cars-tab" data-target="my-driver-bookings">Driver bookings</button>
</div>
<div class="container" style="margin-top: 24px;">
  <div class="bookings-ul active" id="my-drivers">
    <ul class="user-bookings-ul">
      <% @cars.each do |car| %>
        <li class="user-bookings-li">
          <div class="user-bookings-box-1">
            <div class="user-bookings-box-2">
              <div class="user-bookings-box-3">
                <%= cl_image_tag car.photos[0].key, class:"user-bookings-img-box" %>
              </div>
              <div>
                <div class="user-bookings-date-box">
                <div><%= car.address %></div>
                </div>
                <div class="user-bookings-drivername-box">
                  <h4><%= driver.name %> - <%= driver.status %></h4>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="bookings-ul" id="my-driver-bookings">
    <ul class="user-bookings-ul">
      <% @incoming_bookings.each do |your_booking| %>
        <li class="user-bookings-li">
          <div class="user-bookings-box-1">
            <div class="user-bookings-box-2">
              <div class="user-bookings-box-3">
                <%= cl_image_tag your_booking.car.photos[0].key, class:"user-bookings-img-box" %>
              </div>
              <div>
                <div class="user-bookings-date-box">
                <div><%= your_booking.start_date.strftime("%b %d, %Y") %> - <%= your_booking.end_date.strftime("%b %d, %Y") %></div>
                </div>
                <div class="user-bookings-drivername-box">
                  <h4><%= your_booking.driver.name %> - <%= your_booking.driver.status %></h4>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <h1 class="headers">Your bookings</h1>
</div>
<div class="container mt-4 border-bottom border-warning border-10 d-flex justify-content-start">
  <button class="btn btn-bookings booking-tab" data-target="upcoming-bookings">Upcoming</button>
  <button class="btn btn-bookings booking-tab" data-target="past-bookings">Past</button>
</div>
<div class="container" style="margin-top: 24px;">
  <div class="bookings-ul active" id="upcoming-bookings">
    <ul class="user-bookings-ul">
      <% @upcoming_bookings.each do |your_booking| %>
        <li class="user-bookings-li">
          <div class="user-bookings-box-1">
            <div class="user-bookings-box-2">
              <div class="user-bookings-box-3">
                <%= cl_image_tag your_booking.driver.photos[0].key, class:"user-bookings-img-box" %>
              </div>
              <div>
                <div class="user-bookings-date-box">
                <div><%= your_booking.start_date.strftime("%b %d, %Y") %> - <%= your_booking.end_date.strftime("%b %d, %Y") %></div>
                </div>
                <div class="user-bookings-drivername-box">
                  <h4><%= your_booking.driver %> - <%= your_booking.driver %></h4>
                  <!-- <h6  class="edit-buttton">Edit</h6>
                  <h6 class="edit-buttton">Delete</h6> -->
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="bookings-ul" id="past-bookings">
    <ul class="user-bookings-ul">
      <% @past_bookings.each do |your_booking| %>
        <li class="user-bookings-li">
          <div class="user-bookings-box-1">
            <div class="user-bookings-box-2">
              <div class="user-bookings-box-3">
                <%= cl_image_tag your_booking.driver.photos[0].key, class:"user-bookings-img-box" %>
              </div>
              <div>
                <div class="user-bookings-date-box">
                <div><%= your_booking.start_date.strftime("%b %d, %Y") %> - <%= your_booking.end_date.strftime("%b %d, %Y") %></div>
                </div>
                <div class="user-bookings-carname-box">
                  <h4><%= your_booking.driver %> - <%= your_booking.driver %></h4>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>